/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import agenciasisii.Conexion;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;

/**
 *
 * @author gunnar
 */
public class IUContrato extends javax.swing.JFrame {

    boolean esnuevo = false;
    Conexion connec;
    
    
    ArrayList<Integer> lsPais = new ArrayList<>();
    ArrayList<Integer> lsCargo = new ArrayList<>();
    
    int ID_EMP;
    String NOMBRE_EMP;
    String DIRECCION_EMP;
    int PAIS_EMP;
    String CI_EMP;
    String APELLIDO_EMP;
    
    int ID_CARGO_CONT;
    int SALARIO_CONT;
    String FECHAINI_CONT;
    String FECHAFIN_CONT;
    String FECHAACT_CONT;
    String DESCRIPCION_CONT;
    

    public IUContrato(Conexion con,boolean esnuevo) {
        
        try {
            this.esnuevo=esnuevo;
            initComponents();
            initV();
            this.connec = con;
            getPaises();
            getCargos();
            llenarFechaActual();
        } catch (SQLException ex) {
            Logger.getLogger(IUContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /* crea la renovacion de un contrato para esto recibe
        el carnet de un empleado
    */
    IUContrato(Conexion con,String ci){
        //connec.conectar();
        this.connec=con;
        initComponents();
        initV();
        llenarFormularioEmpleadoExiste(ci);
        
        
        try {
            getCargos();
            llenarFechaActual();
        } catch (SQLException ex) {
            Logger.getLogger(IUContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Empleado");

        jLabel2.setText("Nombress");

        jTextField1.setText("jhghjj");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Pais");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Direccion");

        jLabel6.setText("Contrato");

        jLabel7.setText("Cargo");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Salario");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha Inicio");

        jLabel10.setText("Fecha Fin");

        jLabel11.setText("Fecha");

        jLabel12.setText("Descripcion");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel13.setText("CI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 289, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField9))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(esnuevo){  //si es el registro de un nuevo empleado y un nuevo contrato
                insertarNuevoEmpleado();
                insertarContrato();
            
            }
            else{   //si ya existe el empleado y es renovacion de contrato
            
                insertarContrato();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(IUContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IUContrato().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(IUContrato.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
*/
    private void initV(){
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void insertarNuevoEmpleado() throws SQLException{
    
        if(esnuevo){
            
            NOMBRE_EMP = jTextField1.getText().toString();
            PAIS_EMP=lsPais.get(jComboBox1.getSelectedIndex());
            DIRECCION_EMP = jTextField3.getText().toString();
            CI_EMP=jTextField9.getText().toString();
            APELLIDO_EMP=jTextField2.getText().toString();
            
            String consulta  = "SELECT insertarEmpleado('" + NOMBRE_EMP + "', "
                                                            + PAIS_EMP + ", '" 
                                                            + DIRECCION_EMP + "','"
                                                            +CI_EMP+"','"
                                                            + APELLIDO_EMP+"');";

            ResultSet res = connec.resultado(consulta);
            res.next();
            
                    
        }
    }
    
    private void insertarContrato() throws SQLException{
    
        
          
            ID_EMP=buscarIdEmpleado(CI_EMP);
            SALARIO_CONT=Integer.parseInt(jTextField4.getText().toString());
            FECHAINI_CONT=jTextField5.getText().toString();
            FECHAFIN_CONT=jTextField6.getText().toString();
            FECHAACT_CONT=jTextField7.getText().toString();
            DESCRIPCION_CONT=jTextField8.getText().toString();
            
            borrarEmp_Cargo();
            llenarCargo();
            
            String consulta  = "SELECT insertarContrato(1,"
                                + ID_EMP+" , "    //idemp
                                + lsCargo.get(jComboBox2.getSelectedIndex())+ " , "
                                + SALARIO_CONT
                                +", '"+ FECHAINI_CONT+ "', '" 
                                + FECHAFIN_CONT + "', '"
                                + FECHAACT_CONT + "', '"
                                + DESCRIPCION_CONT + "'"
                                +");";                                        

            ResultSet res = connec.resultado(consulta);
            res.next();
            
                    
        
    }
    private int buscarIdEmpleado(String ci) throws SQLException{
        int id=0;
        String funcion="select * from buscarEmp('"+ ci+"');";
        ResultSet res=connec.resultado(funcion);
        if(res.next()){
            id=res.getInt(1);
        }
        return id;
    }
    private void borrarEmp_Cargo() throws SQLException{
        
        int idCargo=lsCargo.get(jComboBox2.getSelectedIndex());
        String consulta="select * from borraremp_cargo("+ID_EMP+","+idCargo+");";
        ResultSet res=connec.resultado(consulta);
        res.next();
        
    }
    
    private void getPaises() throws SQLException{
    
        String consulta = "SELECT * FROM getPaises();";
        ResultSet res = connec.resultado(consulta);
        jComboBox1.removeAllItems();
        while(res.next()){
            
           jComboBox1.addItem(res.getString(2));
            lsPais.add(res.getInt(1));
        }
    }
    
    private void getCargos() throws SQLException{
    
        String consulta = "SELECT * FROM getCargos();";
        ResultSet res = connec.resultado(consulta);
        jComboBox2.removeAllItems();
        while(res.next()){
            
           jComboBox2.addItem(res.getString(2));
            lsCargo.add(res.getInt(1));
       }
    }
    
    public void llenarFormularioEmpleadoExiste(String ci){
    
        String funcion="select * from buscarEmp('"+ ci+"');";
        
        ResultSet res=connec.resultado(funcion);
        try {
            while(res.next()){
                ID_EMP=res.getInt(1);
                PAIS_EMP=res.getInt(2);
                NOMBRE_EMP=res.getString(3);
                DIRECCION_EMP=res.getString(4);
                CI_EMP=res.getString(5);
                APELLIDO_EMP=res.getString(6);
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(IUContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        jTextField1.setText(NOMBRE_EMP);
        jTextField2.setText(APELLIDO_EMP);
        jTextField9.setText(CI_EMP);
        jTextField3.setText(DIRECCION_EMP);
        
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField9.setEnabled(false);
        jTextField3.setEnabled(false);
        
        jComboBox1.removeAllItems();
       // jComboBox1.addItem(String.valueOf(PAIS_EMP));
        llenarPaisEmpleado();
        jComboBox1.setEnabled(false);
            
    
    }
    
    public void llenarPaisEmpleado(){
     
        
        String consulta="select * from getPais("+PAIS_EMP+");";
        ResultSet res=connec.resultado(consulta);
        try {
            if(res.next()){
                jComboBox1.addItem(res.getString(2));
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(IUContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void llenarCargo(){
        try {
            int idCargo=lsCargo.get(jComboBox2.getSelectedIndex());
            
            
            String consulta="select * from setCargoEmp("+ID_EMP+","+idCargo+");";
            ResultSet res=connec.resultado(consulta);
            res.next();
        } catch (SQLException ex) {
            Logger.getLogger(IUContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void llenarFechaActual() throws SQLException{
        String fecha="";
        ResultSet res=connec.resultado("select current_date ;");
        if(res.next()){
            fecha=res.getString(1);
        }
        jTextField7.setText(fecha);
        jTextField7.setEnabled(false);
    
    }  
    
    
}
